url: "https://flus.fr/carnet/"
url_flus: "https://flus.fr/"
title: "carnet de flus"
subtitle: "le blog d’un média social citoyen"
author: "Marien"
timezone: "Europe/Paris"
blog_slug: "index"
websub_hub: "https://websub.flus.io/"

development:
    url: "filesystem"
