url: "https://flus.fr/carnet/"
url_flus: "https://flus.fr/"
title: "Carnet de Flus"
subtitle: "blog d’un média social de veille"
author: "Marien"
timezone: "Europe/Paris"
blog_slug: "index"
websub_hub: "https://websub.flus.io/"
uuid: "d836fc75-3412-5caf-91e2-2fad31343882"
twitter: "@flus_fr"

development:
    url: "filesystem"
