url: "https://flus.io/carnet/"
title: "carnet de flus"
subtitle: "où l’on apprend à vivre de logiciel libre"
author: "Marien"
timezone: "Europe/Paris"
blog_slug: "index"

development:
    url: "filesystem"
